#!/usr/bin/env python3
"""Rebuild the 07_Wiki index layer for a PARA-style Obsidian vault.

This script is intentionally deterministic and non-LLM. It scans source notes in
00_Inbox through 06_Metadata, then rewrites generated index files in 07_Wiki.
It never edits raw source notes.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SOURCE_DIRS = [
    "00_Inbox",
    "01_Projects",
    "02_Areas",
    "03_Resources",
    "04_Archive",
    "05_Attachments",
    "06_Metadata",
]

GENERATED_NOTICE = "<!-- AUTO-GENERATED by knowledge-curator/scripts/rebuild_wiki_index.py; do not edit by hand. -->"
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n?", re.DOTALL)
WIKILINK_RE = re.compile(r"(?<!!)\[\[([^\]]+)\]\]")


@dataclass
class NoteRecord:
    path: str
    title: str
    layer: str
    size: int
    mtime: str
    sha256: str
    type: str
    tags: list[str]
    parent: str
    wikilinks: list[str]
    outgoing_count: int
    inbound_count: int = 0
    has_frontmatter: bool = False


def main() -> int:
    parser = argparse.ArgumentParser(description="Rebuild 07_Wiki index files from 00-06 source notes.")
    parser.add_argument("--vault", default=".", help="Vault root. Defaults to current working directory.")
    parser.add_argument("--wiki", default="07_Wiki", help="Wiki directory relative to vault root.")
    parser.add_argument("--dry-run", action="store_true", help="Scan and report without writing files.")
    parser.add_argument("--max-recent", type=int, default=80, help="Number of recent notes to list in recent.md.")
    parser.add_argument("--json", action="store_true", help="Print summary as JSON.")
    args = parser.parse_args()

    vault = Path(args.vault).expanduser().resolve()
    wiki = (vault / args.wiki).resolve()
    if not vault.exists():
        raise SystemExit(f"Vault does not exist: {vault}")

    wiki.mkdir(parents=True, exist_ok=True)
    records = scan_notes(vault)
    wiki_records = scan_wiki_pages(vault, wiki)
    health = build_health(records, wiki_records)
    generated_at = datetime.now().astimezone().replace(microsecond=0).isoformat()

    outputs = {
        wiki / "index.md": render_index(records, wiki_records, health, generated_at),
        wiki / "source-map.md": render_source_map(records, generated_at),
        wiki / "recent.md": render_recent(records, generated_at, args.max_recent),
        wiki / "health.md": render_health(health, generated_at),
        wiki / "manifest.json": json.dumps(
            {
                "generated_at": generated_at,
                "vault": str(vault),
                "source_dirs": SOURCE_DIRS,
                "counts": build_counts(records, wiki_records),
                "notes": [asdict(record) for record in records],
                "wiki_pages": [asdict(record) for record in wiki_records],
                "health": health,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
    }

    if not args.dry_run:
        for path, content in outputs.items():
            write_text(path, content)
        append_log(wiki / "log.md", generated_at, records, health)

    summary = {
        "vault": str(vault),
        "wiki": str(wiki),
        "dry_run": args.dry_run,
        "source_notes": len(records),
        "wiki_pages": len(wiki_records),
        "missing_frontmatter": len(health["missing_frontmatter"]),
        "broken_wikilinks": len(health["broken_wikilinks"]),
        "generated_files": [str(path.relative_to(vault)) for path in outputs],
    }
    if args.json:
        print(json.dumps(summary, ensure_ascii=False, indent=2))
    else:
        print(
            "Rebuilt wiki index"
            f" | source_notes={summary['source_notes']}"
            f" | wiki_pages={summary['wiki_pages']}"
            f" | missing_frontmatter={summary['missing_frontmatter']}"
            f" | broken_wikilinks={summary['broken_wikilinks']}"
            f" | dry_run={args.dry_run}"
        )
    return 0


def scan_notes(vault: Path) -> list[NoteRecord]:
    records: list[NoteRecord] = []
    all_paths: set[str] = set()
    note_names: dict[str, list[str]] = defaultdict(list)

    for layer in SOURCE_DIRS:
        root = vault / layer
        if not root.exists():
            continue
        for path in root.rglob("*.md"):
            if should_skip(path):
                continue
            rel = relpath(path, vault)
            all_paths.add(rel)
            note_names[path.stem].append(rel)

    for layer in SOURCE_DIRS:
        root = vault / layer
        if not root.exists():
            continue
        for path in sorted(root.rglob("*.md")):
            if should_skip(path):
                continue
            record = build_record(path, vault, layer)
            records.append(record)

    inbound = inbound_counts(records, all_paths, note_names)
    for record in records:
        record.inbound_count = inbound[record.path]
    return sorted(records, key=lambda record: record.path)


def scan_wiki_pages(vault: Path, wiki: Path) -> list[NoteRecord]:
    if not wiki.exists():
        return []
    records: list[NoteRecord] = []
    for path in sorted(wiki.rglob("*.md")):
        if should_skip(path):
            continue
        records.append(build_record(path, vault, "07_Wiki"))
    return records


def build_record(path: Path, vault: Path, layer: str) -> NoteRecord:
    text = read_text(path)
    frontmatter, body = parse_frontmatter(text)
    stat = path.stat()
    title = string_value(frontmatter.get("title")) or first_heading(body) or path.stem
    tags = list_value(frontmatter.get("tags"))
    parent = string_value(frontmatter.get("parent"))
    note_type = string_value(frontmatter.get("type"))
    links = normalize_links(WIKILINK_RE.findall(text))
    return NoteRecord(
        path=relpath(path, vault),
        title=title,
        layer=layer,
        size=stat.st_size,
        mtime=datetime.fromtimestamp(stat.st_mtime).astimezone().replace(microsecond=0).isoformat(),
        sha256=hash_text(text),
        type=note_type,
        tags=tags,
        parent=parent,
        wikilinks=links,
        outgoing_count=len(links),
        has_frontmatter=bool(frontmatter),
    )


def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text
    raw = match.group(1)
    data: dict[str, Any] = {}
    current_key = ""
    for line in raw.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("- ") and current_key:
            data.setdefault(current_key, [])
            if isinstance(data[current_key], list):
                data[current_key].append(clean_scalar(stripped[2:]))
            continue
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        current_key = key.strip()
        value = value.strip()
        if value.startswith("[") and value.endswith("]"):
            inner = value[1:-1].strip()
            data[current_key] = [clean_scalar(part) for part in split_inline_list(inner)]
        elif value == "":
            data[current_key] = []
        else:
            data[current_key] = clean_scalar(value)
    return data, text[match.end() :]


def build_health(records: list[NoteRecord], wiki_records: list[NoteRecord]) -> dict[str, Any]:
    all_records = records + wiki_records
    all_paths = {record.path for record in all_records}
    note_names: dict[str, list[str]] = defaultdict(list)
    for record in all_records:
        note_names[Path(record.path).stem].append(record.path)

    broken: list[dict[str, str]] = []
    for record in all_records:
        for target in record.wikilinks:
            if not resolves_link(target, all_paths, note_names):
                broken.append({"from": record.path, "target": target})

    missing_frontmatter = [record.path for record in records if not record.has_frontmatter]
    no_parent = [
        record.path
        for record in records
        if record.layer != "00_Inbox" and record.layer != "05_Attachments" and not record.parent
    ]
    low_link_notes = [record.path for record in records if record.outgoing_count == 0 and record.inbound_count == 0]
    duplicate_titles = [
        {"title": title, "paths": paths}
        for title, paths in sorted(group_by_title(all_records).items())
        if len(paths) > 1
    ]

    return {
        "missing_frontmatter": missing_frontmatter,
        "notes_without_parent": no_parent,
        "broken_wikilinks": broken,
        "isolated_notes": low_link_notes,
        "duplicate_titles": duplicate_titles,
    }


def render_index(
    records: list[NoteRecord],
    wiki_records: list[NoteRecord],
    health: dict[str, Any],
    generated_at: str,
) -> str:
    counts = build_counts(records, wiki_records)
    recent = sorted(records, key=lambda record: record.mtime, reverse=True)[:12]
    by_layer = defaultdict(list)
    for record in records:
        by_layer[record.layer].append(record)

    wiki_by_type = defaultdict(list)
    for record in wiki_records:
        wiki_by_type[record.type or "other"].append(record)

    lines = [
        "---",
        "type: index",
        f"updated: {date_only(generated_at)}",
        "generated: true",
        "---",
        "",
        "# 07_Wiki Agent Entry",
        "",
        GENERATED_NOTICE,
        "",
        "> Agent first reads this page, then uses the generated maps below to locate source notes in `00_Inbox/` through `06_Metadata/`.",
        "",
        "## Generated Maps",
        "",
        "- [[07_Wiki/source-map|Source Map]] - all source notes grouped by PARA layer.",
        "- [[07_Wiki/recent|Recent Changes]] - newest source notes by modified time.",
        "- [[07_Wiki/health|Index Health]] - broken links, missing frontmatter, parent gaps.",
        "- `07_Wiki/manifest.json` - machine-readable index for precise lookup.",
        "",
        "## Counts",
        "",
        f"- Source notes: {counts['source_notes']}",
        f"- Wiki markdown pages: {counts['wiki_pages']}",
        f"- Broken wikilinks: {len(health['broken_wikilinks'])}",
        f"- Missing frontmatter: {len(health['missing_frontmatter'])}",
        f"- Notes without parent: {len(health['notes_without_parent'])}",
        "",
        "## Source Layers",
        "",
    ]

    for layer in SOURCE_DIRS:
        layer_records = by_layer.get(layer, [])
        latest = max((record.mtime for record in layer_records), default="n/a")
        lines.append(f"- `{layer}/` - {len(layer_records)} notes, latest `{latest}`")

    lines.extend(["", "## Recent Source Notes", ""])
    for record in recent:
        lines.append(f"- [[{without_md(record.path)}|{record.title}]] - `{record.layer}` - {date_only(record.mtime)}")

    lines.extend(["", "## Wiki Pages", ""])
    for page_type in sorted(wiki_by_type):
        entries = wiki_by_type[page_type]
        lines.append(f"### {page_type} ({len(entries)})")
        for record in entries:
            if Path(record.path).name in {"index.md", "source-map.md", "recent.md", "health.md", "log.md"}:
                continue
            lines.append(f"- [[{without_md(record.path)}|{record.title}]]")
        lines.append("")

    lines.extend(
        [
            "## Agent Protocol",
            "",
            "1. Read this page first.",
            "2. Use `manifest.json` or [[07_Wiki/source-map]] to find relevant source notes.",
            "3. Read source notes in `00-06` only when needed for detail.",
            "4. Treat `07_Wiki` as the compiled navigation layer; do not edit `00-06` unless the user explicitly asks.",
            "",
            f"_Generated at: {generated_at}_",
            "",
        ]
    )
    return "\n".join(lines)


def render_source_map(records: list[NoteRecord], generated_at: str) -> str:
    by_layer = defaultdict(list)
    for record in records:
        by_layer[record.layer].append(record)

    lines = [
        "---",
        "type: index",
        f"updated: {date_only(generated_at)}",
        "generated: true",
        "---",
        "",
        "# Source Map",
        "",
        GENERATED_NOTICE,
        "",
    ]
    for layer in SOURCE_DIRS:
        entries = sorted(by_layer.get(layer, []), key=lambda record: record.path)
        lines.extend([f"## {layer} ({len(entries)})", ""])
        for record in entries:
            meta = []
            if record.type:
                meta.append(f"type: {record.type}")
            if record.tags:
                meta.append("tags: " + ", ".join(record.tags[:6]))
            if record.parent:
                meta.append(f"parent: {record.parent}")
            suffix = f" - {'; '.join(meta)}" if meta else ""
            lines.append(f"- [[{without_md(record.path)}|{record.title}]]{suffix}")
        lines.append("")
    lines.append(f"_Generated at: {generated_at}_")
    lines.append("")
    return "\n".join(lines)


def render_recent(records: list[NoteRecord], generated_at: str, max_recent: int) -> str:
    recent = sorted(records, key=lambda record: record.mtime, reverse=True)[:max_recent]
    lines = [
        "---",
        "type: index",
        f"updated: {date_only(generated_at)}",
        "generated: true",
        "---",
        "",
        "# Recent Changes",
        "",
        GENERATED_NOTICE,
        "",
    ]
    for record in recent:
        tags = f" tags: {', '.join(record.tags[:6])}" if record.tags else ""
        lines.append(f"- `{record.mtime}` - [[{without_md(record.path)}|{record.title}]] - `{record.layer}`{tags}")
    lines.extend(["", f"_Generated at: {generated_at}_", ""])
    return "\n".join(lines)


def render_health(health: dict[str, Any], generated_at: str) -> str:
    lines = [
        "---",
        "type: index",
        f"updated: {date_only(generated_at)}",
        "generated: true",
        "---",
        "",
        "# Index Health",
        "",
        GENERATED_NOTICE,
        "",
        "## Summary",
        "",
        f"- Missing frontmatter: {len(health['missing_frontmatter'])}",
        f"- Notes without parent: {len(health['notes_without_parent'])}",
        f"- Broken wikilinks: {len(health['broken_wikilinks'])}",
        f"- Isolated notes: {len(health['isolated_notes'])}",
        f"- Duplicate titles: {len(health['duplicate_titles'])}",
        "",
    ]

    add_path_list(lines, "Missing Frontmatter", health["missing_frontmatter"], 120)
    add_path_list(lines, "Notes Without Parent", health["notes_without_parent"], 120)

    lines.extend(["## Broken Wikilinks", ""])
    for item in health["broken_wikilinks"][:200]:
        lines.append(f"- `[[{item['target']}]]` from [[{without_md(item['from'])}]]")
    if len(health["broken_wikilinks"]) > 200:
        lines.append(f"- ... {len(health['broken_wikilinks']) - 200} more")
    lines.append("")

    add_path_list(lines, "Isolated Notes", health["isolated_notes"], 120)

    lines.extend(["## Duplicate Titles", ""])
    for item in health["duplicate_titles"][:80]:
        paths = ", ".join(f"[[{without_md(path)}]]" for path in item["paths"])
        lines.append(f"- {item['title']}: {paths}")
    lines.extend(["", f"_Generated at: {generated_at}_", ""])
    return "\n".join(lines)


def append_log(log_path: Path, generated_at: str, records: list[NoteRecord], health: dict[str, Any]) -> None:
    if log_path.exists():
        text = read_text(log_path).rstrip()
    else:
        text = "---\ntype: log\n---\n\n# Wiki Log\n"
    entry = "\n".join(
        [
            "",
            f"## [{date_only(generated_at)}] rebuild-index | Automated 07_Wiki index refresh",
            "",
            f"- Source notes scanned: {len(records)}",
            f"- Missing frontmatter: {len(health['missing_frontmatter'])}",
            f"- Notes without parent: {len(health['notes_without_parent'])}",
            f"- Broken wikilinks: {len(health['broken_wikilinks'])}",
            "- Generated: index.md, source-map.md, recent.md, health.md, manifest.json",
            "",
        ]
    )
    write_text(log_path, text + entry)


def build_counts(records: list[NoteRecord], wiki_records: list[NoteRecord]) -> dict[str, Any]:
    return {
        "source_notes": len(records),
        "wiki_pages": len(wiki_records),
        "by_layer": dict(Counter(record.layer for record in records)),
        "wiki_by_type": dict(Counter(record.type or "other" for record in wiki_records)),
    }


def inbound_counts(records: list[NoteRecord], all_paths: set[str], note_names: dict[str, list[str]]) -> Counter[str]:
    inbound: Counter[str] = Counter()
    for record in records:
        for target in record.wikilinks:
            resolved = resolve_link(target, all_paths, note_names)
            if resolved:
                inbound[resolved] += 1
    return inbound


def resolves_link(target: str, all_paths: set[str], note_names: dict[str, list[str]]) -> bool:
    return resolve_link(target, all_paths, note_names) is not None


def resolve_link(target: str, all_paths: set[str], note_names: dict[str, list[str]]) -> str | None:
    clean = clean_link_target(target)
    if not clean:
        return None
    candidates = [clean, f"{clean}.md"]
    for candidate in candidates:
        normalized = candidate.replace("\\", "/")
        if normalized in all_paths:
            return normalized
    stem = Path(clean).stem
    matches = note_names.get(stem, [])
    if len(matches) == 1:
        return matches[0]
    return None


def clean_link_target(target: str) -> str:
    target = target.split("|", 1)[0].split("#", 1)[0].strip()
    return target.strip("/")


def normalize_links(raw_links: list[str]) -> list[str]:
    links: list[str] = []
    seen: set[str] = set()
    for raw in raw_links:
        target = clean_link_target(raw)
        if target and target not in seen:
            seen.add(target)
            links.append(target)
    return links


def first_heading(body: str) -> str:
    for line in body.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def group_by_title(records: list[NoteRecord]) -> dict[str, list[str]]:
    grouped: dict[str, list[str]] = defaultdict(list)
    for record in records:
        grouped[record.title].append(record.path)
    return grouped


def add_path_list(lines: list[str], title: str, paths: list[str], limit: int) -> None:
    lines.extend([f"## {title}", ""])
    for path in paths[:limit]:
        lines.append(f"- [[{without_md(path)}]]")
    if len(paths) > limit:
        lines.append(f"- ... {len(paths) - limit} more")
    lines.append("")


def split_inline_list(value: str) -> list[str]:
    if not value:
        return []
    return [part.strip() for part in value.split(",") if part.strip()]


def clean_scalar(value: str) -> str:
    value = value.strip()
    if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        return value[1:-1]
    return value


def string_value(value: Any) -> str:
    if isinstance(value, str):
        return value
    return ""


def list_value(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(item) for item in value if str(item)]
    if isinstance(value, str) and value:
        return [value]
    return []


def without_md(path: str) -> str:
    return path[:-3] if path.endswith(".md") else path


def relpath(path: Path, root: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def date_only(value: str) -> str:
    return value[:10]


def hash_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def should_skip(path: Path) -> bool:
    parts = set(path.parts)
    return ".git" in parts or "node_modules" in parts or ".obsidian" in parts


if __name__ == "__main__":
    raise SystemExit(main())
